blank_issues_enabled: false # Show or hide the Create a blank issue choice when users select New issue.
contact_links:
  - name: "Questions via Kruize Community slack - #autotune"
    url: https://kruizeworkspace.slack.com/archives/C01R7HV4LPN
    about: "Join us for questions, answers or Kruzie related chat. 
  
