name: Test ROS OCP with latest Kruize remote monitoring
on:
  workflow_dispatch:
    inputs:
      kruize_image:
        description: 'Kruize image'
        required: false
        default: 'quay.io/kruize/autotune_operator'
      kruize_image_tag:
        description: 'Kruize image tag'
        required: false
        default: '0.0.16_rm'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update the file
        run: |
          IMAGE_NAME=${{ github.event.inputs.kruize_image }}
          IMAGE_TAG=${{ github.event.inputs.kruize_image_tag }}
  
          echo "IMAGE TAG = $IMAGE_TAG  IMAGE_NAME = $IMAGE_NAME"

          # Setup the committers identity.
          git config user.email "csubrama@redhat.com"
          git config user.name "Chandrakala Subramanyam"

          # Update the script files to the latest version.
          sed -i "s|\${KRUIZE_IMAGE}:\${KRUIZE_IMAGE_TAG}|${IMAGE_NAME}:${IMAGE_TAG}|g" clowdapp.yaml

          # Commit the changes and push the feature branch to origin
          git add .
          git commit -m "Updated Kruize image"
         

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update README'
          branch: 'feature-branch'
          title: '[Do not merge] - PR to trigger PR check tests on EE against ROS OCP with Kruize RM image specified'
