name: Github app Check and Raise Pull Request

on:
  workflow_dispatch:
  
    
jobs:
  check_changes_and_raise_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        
      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
 
          
      - name: Commit and Push Changes       
        
        run: |          
            IMAGE_NAME="quay.io/chandra25ms/autotune"
            IMAGE_TAG="78a06tt"
           
            sed -i "s|\${KRUIZE_IMAGE}:\${KRUIZE_IMAGE_TAG}|${IMAGE_NAME}:${IMAGE_TAG}|g" ./clowdapp.yaml
            
            git config user.name "Chandra"
            git config user.email "csubrama@redhat.com"
            git add clowdapp.yaml
            git commit -m "Replace image and image tag"
         
       
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'Update kruize image'
          title: 'Update kruize image'
          body: 'This pull request updates the kruize image with the latest'
          
   
