name: Install yq and parse

on:
  workflow_dispatch:
  
    
jobs:
  install_yq_and_parse_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Install yq and parse yaml
        run: |
          sudo apt-get update
          sudo apt-get install yq
